wordpress-mobile/circleci-orbs

src/danger/orb.yml
src/ios/orb.yml

Adds new `validate-podspec` command and uses an existing Orb to manage bundle install + caching.

Add validate-podspec command

---

src/ios/orb.yml

This adds a `test` job to the iOS orb to allow easy running of tests with `xcodebuild`.

iOS: Add test job

---

src/ios/orb.yml

The are some updates to make CocoaPods caching more strict:
- Now CircleCI will only fetch the cache for pods/gems if it matches `Podfile.lock` and `Gemfile.lock` exactly.
- Instead of using the `cocoapods-check` plugin, just verify that `Podfile.lock` and `Pods/Manifest.lock` match exactly when deciding if pods should be installed.
This will mean some longer build times because pods will be completely reinstalled on every `Podfile` change (even whitespace) but its better to start from here and make it less strict if we gain more confidence in how that would work.

iOS: More strict CocoaPods caching/checking behaviour

---

src/ios/orb.yml

We have been seeing some failures caused by inconsistent simulator state. This change explicitly boots the required simulator and ensures it is ready for the tests.
You can see the dev Orb for this in use here: https://circleci.com/gh/wordpress-mobile/WordPressKit-iOS/110.

Preboot simulator to improve xcodebuild stability

---

src/ios/orb.yml

This makes the `test` job much more flexible across different projects.
`bundle install`, `pod install` and `carthage update` (this is new) are now all optional steps. Additionally, the directory they are run in is also optional.
You can see the dev Orb from this branch being used successfully in these builds:
- https://circleci.com/gh/wordpress-mobile/AztecEditor-iOS/42 (this has Carthage with no CocoaPods).
- https://circleci.com/gh/wordpress-mobile/WordPressUI-iOS/7 (this has no dependencies)

iOS: Add install-dependencies command to allow better dependencies configuration

---

src/ios/orb.yml

This makes some improvements to how dependency caching works:
- The cache key is more readable (broken over multiple lines).
- We now check if `Podfile.lock` is changed by `pod install` and fail the build if it is.
- Only install dependencies for `validate-podspec` if `bundle-install` is true.
You can see a successful build here: https://circleci.com/gh/wordpress-mobile/MediaPicker-iOS/20
And here is a build that failed because `Podfile.lock` was not up to date: https://circleci.com/gh/wordpress-mobile/MediaPicker-iOS/18

iOS: Make some improvements to caching

---

src/ios/orb.yml

Currently, `workspace` is a required argument of the `test` job. This means that Xcode projects without an `xcworkspace` file cannot be tested.
This change adds optional `project` and `target` params so that Xcode projects without workspaces can be tested.
Here is an example of this working with a `project` param: https://circleci.com/gh/wordpress-mobile/wpxmlrpc/11

 iOS: allow building with -project or -target parameters

---

.circleci/config.yml
README.md

Currently, the Orbs are published to the CircleCI Orb registry on every push to master, automatically incrementing the version. This works well but is a bit restrictive:
- The patch version is always incremented. This breaks semantic versioning since there may have been breaking changes.
- There is no record of releases in the repo.
- A new version is always published, even if the only change was a README edit.
This changes the config so that new versions are published when the repo is tagged. Now we can release a new version by simply creating a new Github release.

Publish when the repository is tagged instead of every push to master

---

.circleci/config.yml
src/android/orb.yml

This adds a new Orb for dealing with some common Android tasks. It currently handles Gradle caching and storing test results.
This will help us to easily add CircleCI to our other Android projects.
Here is an Android build that uses the the orb from this branch: https://circleci.com/workflow-run/9199b0eb-717e-4333-9610-dd0dbd00425f

Add Orb for common Android tasks

---

src/android/orb.yml

This change provides a default CircleCI executor with sensible defaults for Gradle tasks. After iterating on WPAndroid for some time I'm confident these values are a very good starting point for Android builds.
Individual Android projects can override these with their own `gradle.properties` or with command line arguments.
Here is a build using this change: https://circleci.com/workflow-run/2dff4232-4d16-4ff3-aae5-a2bbf2b60714

Android: Add default executor with sensible GRADLE_OPTS defaults

---

src/ios/orb.yml

As suggested by @jklausa, Xcode's "index while building"  can be disabled for CI builds since it gives no benefit there.
This gives a minor, but welcome improvement to build times (around 30s for WPiOS): https://circleci.com/gh/wordpress-mobile/WordPress-iOS/4498

iOS: Disable indexing while building

---

src/android/orb.yml

This adds a new command to invoke a Firebase Test Lab test run and store the test results. It will be useful as we use Firebase Test Lab across more of our projects.
You can see a successful build of Aztec-Android using this here: https://circleci.com/gh/wordpress-mobile/AztecEditor-Android/78

Android: Add firebase-test command

---

src/android/orb.yml

We already have a `save-test-results` command which is used across each Android project. This is a adds a simple new command, `save-lint-results` which does the same thing for Gradle lint tasks. It will reduce duplication and boilerplate across projects.

Android: Add save-lint-results command

---

src/android/orb.yml
src/ios/orb.yml

Currently, it is necessary to provide an explicit cache prefix for every CircleCI job to avoid conflicting caches. This is a small change so that the cache prefix defaults to the job name. It is still possible to override this on a per-job basis.
You can see a WPAndroid build that uses this update [here](https://circleci.com/gh/wordpress-mobile/WordPress-Android/7669).

Use job name as default cache key prefix

---

src/ios/orb.yml

Currently, the Xcode version is hardcoded to 10.1. This allows it to be passed as a parameter as we do for Android.

iOS: Allow xcode version to be specified

---

src/android/orb.yml

It turns out that downloading all test artifacts can be quite slow for large test runs. There is also a chance that log files could contain credentials that we may not want to reveal in CircleCI artifacts.
This is a simple change to only download the test result files (previously is would download logcat logs, videos etc.). Everything else can be accessed by going to the Firebase console.
Here is a test run using this: https://circleci.com/gh/wordpress-mobile/WordPress-FluxC-Android/618

Android: Only download Firebase test results

---

src/ios/orb.yml

The iOS Orb has quite a bit of duplication right now. This is a syntax change only to reduce this by defining the parameters just once and re-using them.
Since they are no longer duplicated I have also added some descriptions for the params.

 iOS: Extract params to reduce duplication

---

src/ios/orb.yml

It turns out that Xcode 10.2 has changed the format of `xcrun simctl list --json` 😞We need this to launch the simulator before running tests.
This is a small update to be compatible with both Xcode 10.2 and earlier versions.
Here is a run with 10.1 (still working): https://circleci.com/gh/wordpress-mobile/WordPressAuthenticator-iOS/225
Here is a run with 10.2 (fails for another reason; Swift versions): https://circleci.com/gh/wordpress-mobile/WordPressAuthenticator-iOS/223

Compatibility with Xcode 10.2 changes to simctl format

---

src/ios/orb.yml

This adds a command to run `pod trunk push` in order to publish pods. It will allow us to automate more of the release process for pods.
You can see that podspec validation still works correctly [here](https://circleci.com/gh/wordpress-mobile/AztecEditor-iOS/306).

iOS: Add command to publish podspec to CocoaPods trunk

---

src/ios/orb.yml

This is a small improvement to how caching works for iOS builds:
- Each dependency type (bundle, cocoapods, carthage is cached separately). This means that if a gem is changed, pods don't need to be updated etc.
- The Xcode version is used in the cache key to ensure things stay separate.
Here is a build that uses the change: https://circleci.com/gh/wordpress-mobile/WordPress-iOS/6948

iOS: Cache each dependency type separately

---

src/ios/orb.yml

The Simplenote-iOS build is [currently failing](https://circleci.com/gh/Automattic/simplenote-ios/8) because it's trying to boot a simulator version (12.1) that is not available in Xcode 10.2.
Requiring the iOS version to be passed shouldn't be necessary as we can just default to the latest. This makes that change. `ios-version` can still be provided to override this if desired.
See that the simulator boots correctly here (build failure is unrelated): https://circleci.com/gh/Automattic/simplenote-ios/23

iOS: Default to latest available iOS version

---

src/ios/orb.yml

Currently, iOS tests can only be run as a job. This usually works great but as soon as any customization is needed, it fails. For example, [Simplenote is failing](https://circleci.com/gh/Automattic/simplenote-ios/24) because its `config.plist` needs to be copied and the job can't do that.
This adds a command, `test`, with the exact same logic as the job. It can now be called in either way. There are no changes to the logic, the job is refactored only.
You can see Simplenote passing with this change here: https://circleci.com/gh/Automattic/simplenote-ios/29

iOS: Allow tests to be run as a command for more flexibility

---

src/ios/orb.yml

By introducing the `test` command in https://github.com/wordpress-mobile/circleci-orbs/pull/24, I inadvertently broke the existing job. This fixes the issue by simply passing through the needed params.
You can see [this build](https://circleci.com/gh/wordpress-mobile/WordPress-iOS/8112) works as expected.

iOS: Fix test job by passing through all parameters

---

src/ios/orb.yml

While investigating https://github.com/wordpress-mobile/WordPress-iOS/issues/11848, I noticed it can be tricky to debug failing iOS tests.
This small change adds the raw `xcodebuild` logs and any crashes from the iOS Simulator as artifacts on the CircleCI job. See the artifacts tab on [this job](https://circleci.com/gh/wordpress-mobile/WordPress-iOS/8281) as an example.

iOS: Store raw xcodebuild logs and iOS Simulator crashes as artifacts

---

.circleci/config.yml
src/git/orb.yml

This adds a new Orb for git and Github tasks. The first is a command, `checkout-as-zip` which replaces the default `checkout` by downloading the current ref from the Github API as a zip.

Add new Orb to download Github repositories as zips

---

src/ios/orb.yml

The `simctl` format has changed in Xcode 11. This updates it

Fix iOS simulator booting on Xcode 11

---

src/git/orb.yml

This adds another git command to do a shallow clone. It will only work for open source repositories as there is no auth in here (yet).

Git: Add shallow checkout command

---

src/android/orb.yml

The current Gradle cache key is imperfect and can remain unchanged for quite some time. This means the cache goes stale and builds slow down. This is a tiny change to append the current date to the key so it is updated at least once a day.

Android: Update Gradle cache at least once a day to ensure it doesn't go stale

---

src/git/orb.yml

The new `shallow-clone` step I added yesterday has been failing in some cases. This updates it to use the same logic as the default checkout step, just changing it to be shallow.
It will now work for closed source repos.

Git: Update shallow clone to use same logic as default CircleCI step

---

src/git/orb.yml

The new shallow checkout has been working great, but it was uncovered in https://github.com/wordpress-mobile/WordPress-iOS/pull/12404 that is not working correctly in forks. This updates it to work both with forks and regular branches.
I have tested this with a fork [here](https://circleci.com/gh/wordpress-mobile/WordPress-iOS/12837) and with a regular branch [here](https://circleci.com/gh/wordpress-mobile/WordPress-iOS/12838).

Git: Update shallow checkout to work with forks

---

src/ios/orb.yml

@SergioEstevao encountered a limitation of the current implementation where it would fail if `Podfile.lock` did not contain a `SPEC REPOS` entry. This is a simple fix for that.
You can see the patch working with MediaPicker-iOS [here](https://circleci.com/gh/wordpress-mobile/MediaPicker-iOS/145).

iOS: Handle case where Podfile.lock has no 'SPEC REPOS' entry

---

src/ios/orb.yml

We have now been using this command successfully with WordPressAuthenticator for a few weeks. This adds a few minor improvements before I start rolling it out more widely:
- It ensures the `$CIRCLE_TAG` matches the version in the podspec.
- Optionally post a success message to Slack.
You can see it working [here](https://circleci.com/gh/wordpress-mobile/WordPressAuthenticator-iOS/871).

iOS: Add Slack notifications and safety checks to publish-podspec

---

src/ios/orb.yml

We're coming closer to hitting our CircleCI limit each month so I'm making a few small changes to improve usage.
This adds improved support for the [CocoaPods CDN Specs repo](https://blog.cocoapods.org/CocoaPods-1.7.2/). CocoaPods 1.8.0 switched to using the CDN specs repo by default so this changes our logic to not download the master specs repo if no explicit repo is given and the version is >= 1.8.0.
You can see this in action on WordPressAuthenticator [here](https://circleci.com/gh/wordpress-mobile/WordPressAuthenticator-iOS/970). In this case it reduces the time to validate the podspec from **~12 minutes to ~3 minutes**.

iOS: Default to CDN specs repo when CocoaPods >= 1.8.0

---

src/ios/orb.yml

This is a simple change to allow providing additional parameters to `pod lib lint`.
It will allow us to resolve an issue we have  on the Aztec-iOS repo by passing the `--include-podspecs` parameter. You can see that working in https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1220.

iOS: Add 'additional-parameters' option to validate-podspec

---

src/ios/orb.yml

The Orbs in this repo have been working really well for us and we are using them across many projects. One slightly annoying detail is that each project is using a slightly different Orb version, usually the latest when it was created.
An easy solution to this is to use flexible versioning in our CircleCI configs. i.e. Specify `wordpress-mobile/ios@1.1` instead of `wordpress-mobile/ios@1.1.2`. This would mean that when an improvement is made and released from this repo, every project starts getting the changes, provided the changes are backwards compatible.
We could start doing that right away, but I would like to make a few small improvements so that maintaining backwards compatibility is easier.
This is a very small change to make the default values in the iOS Orb more predictable. …

iOS: Use more sensible defaults in preparation for a 1.0 release

---

src/ios/orb.yml

When checking the URL to see if it matches, properly handle potentially incorrectly cased URLs.
A failure of this can be seen in [this CI job](https://app.circleci.com/jobs/github/wordpress-mobile/WordPressAuthenticator-iOS/982).

Fix a case-sensitivity issue in spec URL

---

src/ios/orb.yml

In the spirit of improving things around here to do a v1 release (see https://github.com/wordpress-mobile/circleci-orbs/pull/42). This makes some incremental improvements to CocoaPods caching, particularly when CDN Specs are used:
- Cache `~/.cocoapods/repos/trunk`. This is the CDN specs repo. Since only what's needed is downloaded, this is small and can be safely cached.
- Extract the specs caching logic into a command and use it in `publish-podspec` and `validate-podspec`.
These changes make it possible to use CDN specs with WPiOS and reduce _uncached_ build time for `Build Tests` from ~20 minutes to 17 minutes (see [here](https://circleci.com/gh/wordpress-mobile/WordPress-iOS/14272)). Obviously not a huge gain, but every bit helps!
Additionally, this saves up to 1 minute on …

iOS: Improve CocoaPods Specs caching

---

src/ios/orb.yml

This PR attempts to fix an issue with pods installation where new versions of a pod are not fetched from the Cocoapods CDN if an old one is in the local spec repository.

Retry on pod install failure after cleaning the cache

---

src/ios/orb.yml

The issue details are in https://github.com/stedolan/jq/issues/1992, but this doesn’t seem like something we can fix, or even work around while still using `jq` for this particular functionality (if we can’t use the `test` operator, we can’t filter the list, AFAICT).
This change uses a really simple ruby script to parse the list and get us the same data.
**To Test:** On your local machine, run:
```
xcrun simctl list -j | jq -r '[.runtimes[] | select(.name|test("iOS."))] | sort_by(.version) | .[-1] | .version'
```
then
```
ruby -e 'require "json";puts JSON.parse(`xcrun simctl list -j`)["runtimes"].select { |device| device["name"].include?("iOS") }.map { |device| device["version"] }.sort.last'
```
Both should print the same value to the console. If they do, this PR works!

Fix an issue cased by `jq` in catalina

---

src/git/orb.yml

This PR changes the `git checkout` configuration in order to avoid downloading the files from LFS. We use LFS only for resources for enhanced screenshots, so we don't need it on CI right now. 
Also, cloning and checking out may be quicker and we don't risk to exceed the LFS quota limit. 
Test PRs using this branch:
- WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/12927
- WCiOS: https://github.com/woocommerce/woocommerce-ios/pull/1458

Git: don't checkout LFS files

---

src/ios/orb.yml

This PR replaces some `jq` command-line calls with equivalent Ruby code. `jq` crashes in Catalina when using certain operators, and this seems like the easiest way to resolve the issue. 
It works well on https://github.com/wordpress-mobile/WordPress-iOS/pull/12902 and https://github.com/woocommerce/woocommerce-ios/pull/1446, so I'd like to merge this in order to tag a new version for inclusion in those PRs.

Fix jq segfault issues on Catalina

---

src/ios/orb.yml

- Adds additional logging to make things easier to debug
- Avoids using the base cache key – it seems like it will always have the same value, so it could reference a cache that's unrelated.
Fixes issues in https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/158

Fix issues with pod caching

---

src/ios/orb.yml

This PR adds the same changes made in https://github.com/wordpress-mobile/circleci-orbs/pull/46 to the `podspec` validation job.
In theory, this shouldn't be required (as it shouldn't be on `pod install`), but it seems Cocoapods CDN and CircleCI caching system don't work too well together yet.

Update repo on podspec validation

---

src/git/orb.yml

This PR fixes a bug with `shallow-checkout` where the checkout fails if `CIRCLE_BRANCH` is not set, which happens everytime the build is triggered by a `tag`.
This also makes sure that the label of the tag is fetched into the local repository and not only the commit. 
You can see it working in https://github.com/wordpress-mobile/WordPress-iOS/pull/13658

Fix cloning when branch is not set

---

src/ios/orb.yml

This adds steps to `save-xcodebuild-artifacts` to zip and save test output, including `.xcresult` files. (Without zipping first, the `.xcresult` is not saved correctly.)
We were already doing this in the WPiOS project, but this change:
1. Moves the steps into the orb to be reused in other projects.
2. Updates the path to match the changes to test runs in https://github.com/wordpress-mobile/WordPress-iOS/pull/13810.
You can see these changes on the `ci/circleci: Unit Tests` and `ci/circleci: UI Tests` checks on that PR; check the Artifacts tab in CircleCI to see how the test output is saved there.
Note: We will need to merge this PR before https://github.com/wordpress-mobile/WordPress-iOS/pull/13810, but we should wait until that PR is almost ready to merge to sync up with the changes to …

Add steps to zip and save test output

---

src/ios/orb.yml

Reverts wordpress-mobile/circleci-orbs#56
These changes are causing test failures in the WooCommerce iOS repo. I'll revert and work on a better implementation for everywhere the orb is used.

Revert "Add steps to zip and save test output"

---

src/git/orb.yml

This PR adds an option to init and update submodules after having checked out the main repository. 
This is required for some libraries that are imported as submodules into the client project. 
You can see this is action here: https://github.com/wordpress-mobile/WordPress-Android/pull/11877.

Add an option to handle submodule initialization

---

src/android/orb.yml

This change allows the `android/firebase-test` command to take a list of devices, instead of limiting it to only one device.
This is required in order to trigger a Firebase Test Lab run in a single matrix on multiple devices at once.
This is especially needed in order to build the PlayStore promo screenshots for WPAndroid (PR coming soon)
The command now allows 2 new parameters:
- `devices` (plural): a space-or-newline-separated list of device specifiers
- `locales`: a space-or-newline-separated list of locale codes
Note that the old `device` (singular) parameter has been kept for backward-compatibility reasons. Because of this, we couldn't mark the `devices` parameter as required (we had to provide a `default: ""` value).
- The new `devices` parameter takes precedence over the old …

Allow firebase-test command to use a device matrix
